name: Create zip
on:
  workflow_dispatch:
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: /Chars /Maps
          dest: /release.zip
      - run: |
          ls ${{ github.workspace }}
      - name: Upload asset to release
        uses: gacts/upload-to-release@master
        with:
          file: './release.zip'
  #uploadAsset:
   # needs: zip-files
    #runs-on: ubuntu-latest
    #steps:
     # - uses: Shopify/upload-to-release@master
      #  with:
       #   name: release.zip
        #  path: /home/runner/work/MoobaPack/MoobaPack
         # repo-token: ${{ secrets.GITHUB_TOKEN }}
          #content-type: zip
