name: Create Archive
on: [release]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Private actions checkout
      uses: daspn/private-actions-checkout@master
      with:
        actions_list: '["thedoctor0/zip-release@master"]'
        checkout_base_path: ./.github/actions

    - name: Validation
      run: |
        ls -lR ./.github/actions
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'MoobaPack${tag}.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
