name: Create zip
on:
  workflow_dispatch:
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: /Chars /Maps
          dest: /release.zip
  uploadAsset:
    needs: zip-files
    runs-on: ubuntu-latest
    steps:
      - uses: PeerXu/upload-asset@v1
        with:
          file: /release.zip
          suffix: .zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
